stages:
  - test
  - build

lint:
  image: node:latest
  stage: test
  cache:
    paths:
      - node_modules/
      - .yarn/
  script:
    - yarn config set cache-folder .yarn
    - yarn
    - yarn lint

build:
  image: node:latest
  stage: build
  cache:
    paths:
      - node_modules/
      - .yarn/
  script:
    - yarn config set cache-folder .yarn
    - yarn
    - yarn build
  artifacts:
    expire_in: 3 days
    paths:
      - dist
